// src/components/Nav.tsx
import React from "react";
import { NavLink } from "react-router-dom";
import styled from "styled-components";

const Nav = styled.nav`
  display: grid;
  grid-template-columns: 1fr 3fr;
  align-items: center;
`;

const Logo = styled.h1`
  font-size: 1.5em;
  a {
    text-decoration: none;
    color: #333;
  }
`;

const Menu = styled.ul`
  list-style-type: none;
  text-align: right;
  li {
    display: inline;
    padding: 0 1em;
    a {
      text-decoration: none;
      color: #666;
    }
    a.selected {
      color: #333;
      border-bottom: 1px solid #333;
    }
  }
`;

export default function App() {
  return (
    <Nav>
      <Logo>
        <a href="/">#andrewmolyuk</a>
      </Logo>
      <Menu>
        <li>
          <NavLink exact to="/" activeClassName="selected">
            Info
          </NavLink>
        </li>
        <li>
          <NavLink to="/works" activeClassName="selected">
            Works
          </NavLink>
        </li>
        <li>
          <NavLink to="/links" activeClassName="selected">
            Links
          </NavLink>
        </li>
      </Menu>
    </Nav>
  );
}

// src/components/Nav.svelte
<script>
  export let segment;
</script>

<style lang="scss" scoped>
  @import "../global.scss";
  nav {
    display: grid;
    grid-template-columns: 1fr 3fr;
    align-items: center;
    h1 {
      a {
        text-decoration: none;
        color: $font-color;
      }
    }
    ul {
      list-style-type: none;
      text-align: right;
      li {
        display: inline;
        padding: 0 1em;
        a {
          text-decoration: none;
          color: $menu-color;
          padding: 0.3em 0;
        }
        a.selected {
          color: $font-color;
          border-bottom: 1px solid $font-color;
        }
      }
    }
  }
</style>

<nav>
  <h1>
    <a href="/">#andrewmolyuk</a>
  </h1>
  <ul>
    <li>
      <a class:selected="{segment === undefined}" href=".">Info</a>
    </li>
    <li>
      <a class:selected="{segment === 'works'}" href="works">Works</a>
    </li>
    <li>
      <a class:selected="{segment === 'resources'}" href="resources">Resources</a>
    </li>
  </ul>
</nav>
